### ISSUE TITLE
Failure in JSON parsing when ingesting `gesture_scroll` events

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#1184]
## Summary

Sometimes ingestion fails for `gesture_scroll` events while trying to unmarshal integers. See the error from logs below. These requests fail with a `400 Bad Request`.

```
api-1  | failed to parse events payload json: cannot unmarshal number 6519191642 into Go struct field GestureScroll.gesture_scroll.touch_down_time of type uint32            │
```

```
api-1  | failed to parse events payload json: cannot unmarshal number 4630447820 into Go struct field ColdLaunch.cold_launch.process_start_uptime of type uint32
```

These fields are also vulnerable to this issue.

- `gesture_click.touch_down_time`
- `gesture_click.touch_up_time`
- `gesture_long_click.touch_down_time`
- `gesture_long_click.touch_up_time`
- `gesture_scroll.touch_down_time`
- `gesture_scroll.touch_up_time`
- `cold_launch.process_start_uptime`

## Environment Details

| Component | Version |
|--------|--------|
| Measure | v0.1.1 |
| OS | Alpine v3.20 |

**Comment by abhaysood** [comment]
6519191642 is an unusually large value given it represents `uptime` since the device booted.

https://github.com/measure-sh/measure/blob/67b77d2b6e2d00fb37116e8cbc9eb61892c443b8/android/measure/src/main/java/sh/measure/android/gestures/GestureDetector.kt#L67

If we are seeing this, we should update all other timestamps to support 64 bit integers. I'll also investigate more on this.

**Comment by abhaysood** [comment]
The following fields need to change from uint32 to uint64

```
gesture_click.touch_down_time
gesture_click.touch_up_time

gesture_long_click.touch_down_time
gesture_long_click.touch_up_time

gesture_scroll.touch_down_time
gesture_scroll.touch_up_time

http.start_time
http.end_time

cold_launch.process_start_uptime
cold_launch.process_start_requested_uptime
cold_launch.content_provider_attach_uptime
cold_launch.on_next_draw_uptime

warm_launch.app_visible_uptime
warm_launch.on_next_draw_uptime

hot_launch.app_visible_uptime
hot_launch.on_next_draw_uptime

cpu_usage.interval
```

**Comment by detj** [comment]
These events are already `uint64`. Skipping these.

```
http.start_time
http.end_time
```
