### ISSUE TITLE
No lifecycle_fragment events when using r8

### ISSUE THREAD

**Issue by jose-a-rodrigues-alb** [measure-sh/measure#1326]
**SDK bug (please complete the following information):**
 - OS: android 15, android 10
 - SDK Version : android-v0.7.0

**Describe the bug**
If i run the app with **isMinifyEnabled = true** i don't see any **lifecycle_fragment** events on the sessions.
If i run the app with **isMinifyEnabled = false** i see **lifecycle_fragment** events on the sessions as expected.

**To Reproduce**
1. Open the android project on Android Studio
2. Change the valu of **isMinifyEnabled** to true on the app **build.gradle.kts** file for release buildType
3. Run the sample app with measureEnabled 
4. Test the different fragment navigation sections

**Expected behavior**
The session registered on measure should show  **lifecycle_fragment** events for the fragments opened.

**Comment by abhaysood** [comment]
Thanks for spotting this @jose-a-rodrigues-alb. 🙇 
I've raised a PR with the fix.

**Comment by jose-a-rodrigues-alb** [comment]
thank you for your support @abhaysood .

Best regards
