### ISSUE TITLE
Cancel previous  inflight requests

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#1432]
## Summary

If an ongoing request is in progress and another incoming request appears, cancel all previous ongoing requests and let the latest request take over.

## Implementation

All requests go through `fetchAuth` function in `auth.ts`, we can modify the function to cancel previous requests by maintaining a queue of ongoing requests and cancel previous ones using [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

**Comment by anupcowkur** [comment]
closed by #1470
