### ISSUE TITLE
Checkpoints not visible in trace detail page

### ISSUE THREAD

**Issue by abhaysood** [measure-sh/measure#1594]
# Description

See the video below, the checkpoints are not visible on the trace detail page graph, but are visible in the overlay panel.

<img width="1728" alt="Screenshot 2024-12-12 at 9 52 41 AM (2)" src="https://github.com/user-attachments/assets/8826193d-1f10-48c1-8591-26d46f9d8845" />

**Comment by anupcowkur** [comment]
closed by #1606
